### ISSUE TITLE
Add backdoored to jar name

### ISSUE THREAD

**Issue by snuckdev** [Crystallinqq/PyroClientReup#3]
Please, add the BackdooredByCrystalinqq in the jar name. Thanks!

**Comment by Crystallinqq** [comment]
send proof that its backdoored and i will :^)

**Comment by gqbe** [comment]
> Please, add the BackdooredByCrystalinqq in the jar name. Thanks!

hi!! its not backdoored, its just a crappy paste to save u 20 bucks :)

**Comment by snuckdev** [comment]
> send proof that its backdoored and i will :^)

So what did you modified?

**Comment by snuckdev** [comment]
I don't want to fight with you, I only want to know what you modified.

**Comment by gqbe** [comment]
> > send proof that its backdoored and i will :^)
> 
> So what did you modify?

He didnt modify anything actually! :)

**Comment by Crystallinqq** [comment]
Modified the LoadingPluginImpl to print credits

**Comment by snuckdev** [comment]
Hmm Ok
