### ISSUE TITLE
Prove to me that it is a backdoor

### ISSUE THREAD

**Issue by FerrumTheElement** [Crystallinqq/PyroClientReup#6]
Prove to me that it is a backdoor Crystallinqq

**Comment by Crystallinqq** [comment]
it is not a backdoor so?

**Comment by Desu-Sureiya** [comment]
ya................crystallinqq never said it was a backdoor...........

**Comment by BLUELIGHTTIGER** [comment]
Hey maybe this isnt backdoor cau dev from other client didnt grab their codes this time so trust on them atleast or spend your money on such a client who viloating minecraft eula.
