### ISSUE TITLE
@Crystallinqq you are real hero because you are not earning money from your knolwlage

### ISSUE THREAD

**Issue by BLUELIGHTTIGER** [Crystallinqq/PyroClientReup#9]
I am waiting for phobos version 1.8.9 and please optimise phobos also are you trying to crack rusherhacks. @Crystallinqq ☺

**Comment by BLUELIGHTTIGER** [comment]
I forgot to ask how to install nedd forge or just past into version folder

**Comment by Crystallinqq** [comment]
no i am not going to crack rusherhack again most likely. i dont work on phobos. its for forge 1.12.2
